# This file was generated by GoReleaser. DO NOT EDIT.
cask "stunt" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "3e581bbef7f6e09ebc4990651344689502826a8cd1037a7bf96ca57dec7ecd57"
      url "https://github.com/stuntapi/stunt/releases/download/v#{version}/stunt_#{version}_Darwin_amd64.tar.gz",
        verified: "github.com/stuntapi/stunt"
    end
    on_arm do
      sha256 "be6a188733fd4bafb56bb73b0fa9af1ebf3385e43a863de63507cc8901de5d8f"
      url "https://github.com/stuntapi/stunt/releases/download/v#{version}/stunt_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/stuntapi/stunt"
    end
  end

  on_linux do
    on_intel do
      sha256 "e570a4b08d3caa80159748fe4f821b75502b9958280f952a91d45826ce8fb656"
      url "https://github.com/stuntapi/stunt/releases/download/v#{version}/stunt_#{version}_Linux_amd64.tar.gz",
        verified: "github.com/stuntapi/stunt"
    end
    on_arm do
      sha256 "747103a53330006955deb13d145c9d88630a6f30174458b6411711d7d6fa3b0b"
      url "https://github.com/stuntapi/stunt/releases/download/v#{version}/stunt_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/stuntapi/stunt"
    end
  end

  name "stunt"
  desc "Local simulators for public APIs — mock/stub servers for testing without remote accounts."
  homepage "https://stuntapi.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stunt"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stunt"]
  end

  # No zap stanza required

  caveats <<~EOS
    stunt is a local-only testing tool. Reference adapters ("*-style") are
    unofficial, synthetic-data simulators, not affiliated with any provider.
  EOS
end
