# This file was generated by GoReleaser. DO NOT EDIT.
cask "stunt" do
  version "0.29.0"

  on_macos do
    on_intel do
      sha256 "38eefb2ad684841b7343a4d8e331722e7860a6f569852aa7915b8a5bd089a4de"
      url "https://github.com/stuntapi/stunt/releases/download/v#{version}/stunt_#{version}_Darwin_amd64.tar.gz",
        verified: "github.com/stuntapi/stunt"
    end
    on_arm do
      sha256 "c1a9113a53d00080634a0ec79ddb11484a4da6cbe4250efebc5161efaab243a1"
      url "https://github.com/stuntapi/stunt/releases/download/v#{version}/stunt_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/stuntapi/stunt"
    end
  end

  on_linux do
    on_intel do
      sha256 "987ffb5ad258ce3d19bd4a766b60f6904ad79ba82faf9c0f2de42c1de78cd9e6"
      url "https://github.com/stuntapi/stunt/releases/download/v#{version}/stunt_#{version}_Linux_amd64.tar.gz",
        verified: "github.com/stuntapi/stunt"
    end
    on_arm do
      sha256 "62fe6e20190ac56080fed58932f42ca5f2defb56421dfed7999ca6caec8d9bf6"
      url "https://github.com/stuntapi/stunt/releases/download/v#{version}/stunt_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/stuntapi/stunt"
    end
  end

  name "stunt"
  desc "Local simulators for public APIs — mock/stub servers for testing without remote accounts."
  homepage "https://stuntapi.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stunt"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stunt"]
  end

  # No zap stanza required

  caveats <<~EOS
    stunt is a local-only testing tool. Reference adapters ("*-style") are
    unofficial, synthetic-data simulators, not affiliated with any provider.
  EOS
end
