# This file was generated by GoReleaser. DO NOT EDIT.
cask "stunt" do
  version "0.21.0"

  on_macos do
    on_intel do
      sha256 "1c503ef1ab0886206fe8b1ad26ecc734e51bc9f556bdc48896d374f3c43400c2"
      url "https://github.com/stuntapi/stunt/releases/download/v#{version}/stunt_#{version}_Darwin_amd64.tar.gz",
        verified: "github.com/stuntapi/stunt"
    end
    on_arm do
      sha256 "489d6c7b23c53a417c5ba1a10846172769454a0c7e5c5c64ee88d1ef1de9aee2"
      url "https://github.com/stuntapi/stunt/releases/download/v#{version}/stunt_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/stuntapi/stunt"
    end
  end

  on_linux do
    on_intel do
      sha256 "03cd7a935d3e47a76544266bd9631f55144f62e88a3781564055e5ebd9d6062a"
      url "https://github.com/stuntapi/stunt/releases/download/v#{version}/stunt_#{version}_Linux_amd64.tar.gz",
        verified: "github.com/stuntapi/stunt"
    end
    on_arm do
      sha256 "8288ff0f7d9ca5006a8459b9ccc79e0201213df45df169a139707979fa4d0832"
      url "https://github.com/stuntapi/stunt/releases/download/v#{version}/stunt_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/stuntapi/stunt"
    end
  end

  name "stunt"
  desc "Local simulators for public APIs — mock/stub servers for testing without remote accounts."
  homepage "https://stuntapi.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stunt"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stunt"]
  end

  # No zap stanza required

  caveats <<~EOS
    stunt is a local-only testing tool. Reference adapters ("*-style") are
    unofficial, synthetic-data simulators, not affiliated with any provider.
  EOS
end
